name: Frontend CI/CD

on:
  push:
    branches:
      - main
    
      #path of the frontend folder

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mynotes


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: setup node.js
      uses: actions/setup-node@v4
      with: 
        node-version: 20

    - name: install depenedices
      run: npm install

    - name: Create .env
      run: |
        echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > .env

    - name: build
      run : npm run build

    - name: configure aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: deploy to s3
      run: aws s3 sync build/ s3://${{secrets.AWS_BUCKET_NAME}} --delete

      #with --delete github removes old files



    
